### ISSUE TITLE
rename `trace` to `stack`

### ISSUE THREAD

**Issue by rspieker** [konfirm/node-blame#1]
As `stack` is more commonly used in javascript (`new Error('...').stack`) when referring to _stack traces_, it seems appropriate to rename `trace` to `stack` as this would be more intuitive.

(At least an alias could be added so both are available)

**Comment by pauldenotter** [comment]
I guess an alias should do the job. Maybe deprecate trace? That would also make this a non-breaking change, so no major version change required! :smile:

**Comment by rspieker** [comment]
Thanks for the feedback!
I wouldn't have thought to use the built-in `util.deprecate` to make it a non-breaking change, thanks for the idea!
